### ISSUE TITLE
Hard to use code.

### ISSUE THREAD

**Issue by mslmanni1** [JahnStar/Hey-Area-Object-Spawner#1]
Hard to use code as variables and functions don't use English naming.
It would help if you use English naming convention so that everyone can use this for their projects.

**Comment by Thundros** [comment]
I'll translate it at some point.

**Comment by JahnStar** [comment]
English naming was used in the code. https://github.com/JahnStar/Hey-Area-Object-Spawner/commit/69ef5f160db8888c820f50e4556a70d47b4e89fe
Language toolbar option added to Inspactor.
