### ISSUE TITLE
Please make this free from DLLs!

### ISSUE THREAD

**Issue by Thundros** [JahnStar/Hey-Area-Object-Spawner#2]
Hi @JahnStar! First off, I'd like to say : HATS OFF TO YOU! This is a work of ART! KUDOS to you my brother! PLEASE keep working on this BEAUTIFUL work of art! <3 Second, I'm having a hard time understanding some of the functions being used in some of the code. I am studying the code in order to learn procedural generation of plants & I think that some of these functions may rely on the use of a DLL file. I would like to ask if you could possibly make this DLL-free. In other words, I would like to ask if you could possibly put the Source code of the DLL into Unity CS form. Or if there's some way you could make it an Open DLL? Either way. Anyway, once again, KUDOS to you, my friend & keep on keeping on with this project! It's BEAUTIFUL! <3

Sincerely, 

Thundros

**Comment by Thundros** [comment]
@JahnStar  ???

**Comment by JahnStar** [comment]
Firstly, thank you! I haven't planned anything about the DLL for now. To be honest, I don't have much time... However, maybe I can make it open source in new release. By the way, all DLL functions are referenced in the project. You can use DLL functions. <3

**Comment by Thundros** [comment]
@JahnStar : Would be GREAT if you could open source it! I wouldn't mind if you wouldn't mind! ^_^ MUCH thanks brother! Please keep on keeping on! <3 When can you open source the DLL? I would love to learn how it works!

**Comment by JahnStar** [comment]
I don't know when but I will upload a different version of this to the asset store. I could recode the DLL file at the same time. Thanks again for your interest.

**Comment by JahnStar** [comment]
The library is now open-source.
