### ISSUE TITLE
Cant create zones

### ISSUE THREAD

**Issue by Krizo220** [JahnStar/Hey-Area-Object-Spawner#3]
Cant create zones in unity 2020.3.22f1
When I try to Ctrl+Shift+Right(or Left)click on the terrain it just select both of them.
I tried creating a fresh empty project, still didn't work.

**Comment by JahnStar** [comment]
Sorry for my late reply.
I tested it now and it still works until Unity 2020.3.31f (latest version)
Maybe there is a bug on the editor.
Try this: Window -> Layouts -> Reset All Layouts

**Comment by JahnStar** [comment]
Or you couldn't see the created area because the point size might be small. Set point size and line thickness to max from HeyAreaSpawner -> Settings, Try Shift+Click and Shift+Click again on different zone.
