### ISSUE TITLE
Unity 2021.3.9 Crashing Editor

### ISSUE THREAD

**Issue by trurkowski** [JahnStar/Hey-Area-Object-Spawner#4]
Hello - We have just updated editor versions on my team to unity 2021.3.9 - and unfortunately when spawning even simple mesh+collider prefabs on terrains now, the editor crashes at the moment...

Here is the end of my editor log when I tried to use it with the packaged tree fabs if that is useful.

[Editor-prev End - Censored.log](https://github.com/JahnStar/Hey-Area-Object-Spawner/files/9602370/Editor-prev.End.-.Censored.log)

Love the tool! Hopefully there's a way for me to continue using it

**Comment by damirljubic-onlinearts** [comment]
Hi, 2021.2.7f1 crashing editor on button spawn on opened demo scene.

Asset looks very promising, it's a real shame that it can't be used.

**Comment by JahnStar** [comment]
The crash error has been fixed. Additionally, apologize for the delay.

**Comment by trurkowski** [comment]
Just wanted to say I still really like this asset, I have more complex spawners, but this one is much more efficient to use because of the limited scope. I don't way too much time adjusting settings, and it makes my work go faster. - thank you for fixing!

**Comment by JahnStar** [comment]
Thank you. Glad it's working well for you, happy developing :)
