### ISSUE TITLE
bad placement of trees

### ISSUE THREAD

**Issue by Stigmamax** [JahnStar/Hey-Area-Object-Spawner#5]
Hi,
when I place an area on my land, it's at the lowest point (about 70 meters below), so not on the surface at all.
On the other hand, if I place an area on the demo terrain, it works very well.

**Comment by Stigmamax** [comment]
c'est bon, j'ai mis une note sur Asset Store.

**Comment by Stigmamax** [comment]
personne ici ???

**Comment by JahnStar** [comment]
Sorry for the late reply. Could you share your sample code as a repository with me?"

**Comment by Stigmamax** [comment]
it's solved now. The problem was that I had several lots adjoining the main one. It works well. this tool is really handy.

**Comment by JahnStar** [comment]
Thank you. Although, I'll test what you said when I find the time.

**Comment by Stigmamax** [comment]
If you make a new version, here is an improvement that would be appreciated.
It lacks the rotation on the 3 axes. I have a lot of rocks in my scene and I have to manually rotate them otherwise they always show the same top face. And this work is very long on a 2500 x 2500 plot!
