### ISSUE TITLE
Apply Tool on Plane

### ISSUE THREAD

**Issue by BLRochaGonzalez93** [JahnStar/Hey-Area-Object-Spawner#6]
First that all, sorry about my bad english, it's not my native language, so i will try my best.

I have been trying to use your tool about 1 hour ago, but i couldn't make it works. Lately i tried on a Terrain and it worked correctly, so  my question is if this tool can be applied on a simple Plane instead of a Terrain?

If it is possible, even by modifying or adapting your tool, could you illuminate the way for me?

I'm not a Unity professional, just a student, but I can understand much of the code you use, and I've managed to get to the place where you declare the Terrain variable. My question is if it would be possible and viable to change the code so that it also works on a 3D plane instead of a Terrain.
![HeyArea](https://github.com/JahnStar/Hey-Area-Object-Spawner/assets/99007329/6733cfe9-5a07-4049-8339-f33456bb1fce)

**Comment by JahnStar** [comment]
I've just seen that, sorry if it's too late. I coded this a long time ago, but I guess you can simply remove the line `poz.y = terrain.SampleHeight(poz) + pointHeight;` to prevent recalculating the vertical position.
Feel free to ask if you need more help.
